# Quick way around
language: c

# Install make and curl
addons:
  apt:
    packages:
    - cmake
    - curl
    
# Install Goos for the image build validation step
install:
- curl -fsSL https://goss.rocks/install | sh

# Simple 2 step process:
# 1. Build the image
# 2. Run the image and test it using Goos
script:
- make build
- make test
